name: Movies admin autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linter:
    if: |
      github.ref == 'refs/heads/main' ||
      github.head_ref == 'feature/messenger' ||
      github.head_ref == 'main'
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      # Downloads a copy of the code in your repository before running code quality test
      - name: Checkout code
        uses: actions/checkout@v4
      #Starts flake8 linter
      - name: Test code quality
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          python -m flake8

 
  movies-control-code:
    if: |
      github.ref == 'refs/heads/main' ||
      github.head_ref == 'feature/messenger' ||
      github.head_ref == 'main'
    name: control-code
    needs: [ linter ]
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      # Downloads a copy of the code in your repository before running code quality test
      - name: Checkout code
        uses: actions/checkout@v4
      #Starts sqlfluff linter
      - name: Check Workflow Status
        run: |
          ./.github/workflows/code_generator -t ./.github/workflows/
